PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sc: <http://iiif.io/api/presentation/2#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX as: <http://www.w3.org/ns/activitystreams#>
PREFIX oa: <http://www.w3.org/ns/oa#>
CONSTRUCT {?canvasIRI rdf:type sc:Canvas .
?canvasIRI as:items ?annotationPage .
?mid rdf:first ?anno .
?mid rdf:rest ?last .
?anno rdf:type oa:Annotation }
WHERE {values ?canvasIRI {<http://collectiones.manuscriptorium.com/unescoCzechReformation/AIPDIG-NKCR__OSEK_37_____0D6W3OF-cs/canvas/ID0001r/>} .
GRAPH ?g {?canvasIRI sc:hasImageAnnotations ?annotationPage .
?annotationPage rdf:rest* ?mid .
?mid rdf:first ?anno .
?mid rdf:rest ?last .
}}